on: [pull_request]

jobs:
  test-checks:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: A job to test my checks
    steps:
      - uses: actions/checkout@v3
      - id: checks
        uses: black-desk/checks@black-desk/fix/commitlint
